// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppUpdate is the app-release banner state. Available is true only when the
 * latest stable GitHub release is newer than the running build.
 */
export interface AppUpdate {
    "current": string;
    "latest": string;
    "url": string;
    "available": boolean;
}

/**
 * Bindings contains the three explicit entry-point preset bindings.
 */
export interface Bindings {
    "gui": string;
    "cli": string;
    "contextMenu": string;
}

/**
 * CollisionPrompt describes one waiting output-exists decision. It is emitted
 * as "collision-prompt" and answered through ResolveCollision.
 */
export interface CollisionPrompt {
    "input": string;
    "output": string;
}

/**
 * CommandPreview is the resolved cjxl command for one preset rule.
 */
export interface CommandPreview {
    "matches": string[] | null;
    "command": string;
}

/**
 * ConversionOptions are the temporary GUI settings applied to a preset for one
 * run. The stored preset is never modified by these overrides.
 */
export interface ConversionOptions {
    "preset": string;
    "processes": number;
    "threads": number;
    "jpegMode": string;
    "distance": number;
    "useDistance": boolean;
    "useQuality": boolean;
    "effort": number;
    "useEffort": boolean;
    "outputPolicy": string;
    "expertFlags": FlagOverride[] | null;
    "resetExpert": boolean;
}

/**
 * ConversionSummary is emitted when a run finishes.
 */
export interface ConversionSummary {
    "total": number;
    "completed": number;
    "failed": number;
    "skipped": number;
    "cancelled": boolean;
    "bytesIn": number;
    "bytesOut": number;
}

/**
 * FilePreview is one item in the Basic view before conversion starts.
 */
export interface FilePreview {
    "path": string;
    "name": string;
    "format": string;
    "route": string;
    "size": number;
    "skip": boolean;
    "reason": string;
    "settings": string;
    "flagsSet": boolean;
}

/**
 * FileUpdate is emitted when one file finishes.
 */
export interface FileUpdate {
    "input": string;
    "output": string;
    "format": string;
    "route": string;
    "inputSize": number;
    "outputSize": number;
    "skipped": boolean;
    "skipReason": string;
    "cancelled": boolean;
    "error": string;
}

/**
 * FlagInfo describes one generated cjxl flag for the Expert UI.
 */
export interface FlagInfo {
    "key": string;
    "short"?: string;
    "long"?: string;
    "takesValue": boolean;
    "valueSpec"?: string;
    "section"?: string;
    "description"?: string;
}

/**
 * FlagOverride is a temporary global cjxl flag override for one conversion.
 */
export interface FlagOverride {
    "key": string;
    "value": string;
    "valueless": boolean;
}

/**
 * HistoryEntry is one successful conversion shown by the History view.
 */
export interface HistoryEntry {
    "at": string;
    "input": string;
    "output": string;
    "route": string;
    "preset": string;
    "inputSize": number;
    "outputSize": number;
}

/**
 * PresetCore is the readable core of a preset: distance, effort, JPEG mode,
 * output policy and the extra cjxl flags of the fallback ("*") rule. The GUI
 * snapshots it via GetPresetCore when a preset is selected and uses the
 * snapshot for the dirty check and the Revert action.
 */
export interface PresetCore {
    "name": string;
    "readOnly": boolean;
    "distance": number;
    "useQuality": boolean;
    "effort": number;
    "jpegMode": string;
    "policy": string;
    "flags": FlagOverride[] | null;
}

/**
 * PresetRuleSummary is one file-filter rule shown in the selected-preset details.
 */
export interface PresetRuleSummary {
    "matches": string[] | null;
    "coreValue": string;
    "effort": string;
    "jpegMode": string;
}

/**
 * PresetSummary is the compact data shown by the Presets view.
 */
export interface PresetSummary {
    "name": string;
    "description": string;
    "policy": string;
    "collision": string;
    "readOnly": boolean;
    "coreValue": string;
    "effort": string;
    "jpegMode": string;
    "rules": PresetRuleSummary[] | null;
}

/**
 * ProgressUpdate is emitted while a conversion is running.
 */
export interface ProgressUpdate {
    "total": number;
    "completed": number;
    "failed": number;
    "skipped": number;
    "inFlight": number;
    "bytesTotal": number;
    "bytesDone": number;
    "throughput": number;
    "etaSeconds": number;
    "coalesced": number;
    "paused": boolean;
    "percent": number;
}

/**
 * Status is a small snapshot the frontend can render on start.
 */
export interface Status {
    "unboundEntryPoints": string[] | null;
    "ready": boolean;
}

/**
 * ToolchainProgress is emitted during a libjxl download/install.
 */
export interface ToolchainProgress {
    "phase": string;
    "downloaded": number;
    "total": number;
}

/**
 * ToolchainStatus is the compact toolchain state rendered by the Tools view.
 * Updates are notify-only: querying status never downloads or installs anything.
 */
export interface ToolchainStatus {
    "installedVersion": string;
    "cjxlVersion": string;
    "djxlVersion": string;
    "jxlinfoVersion": string;
    "latestVersion": string;
    "updateAvailable": boolean;
    "needsInstall": boolean;
    "flagsLocked": boolean;
    "flagBaseVersion": string;
    "flagToolVersion": string;
    "addedFlags": string[] | null;
    "removedFlags": string[] | null;
}
