// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Bindings contains the three explicit entry-point preset bindings.
 */
export interface Bindings {
    "gui": string;
    "cli": string;
    "contextMenu": string;
}

/**
 * ConversionOptions are the temporary GUI settings applied to a preset for one
 * run. The stored preset is never modified by these overrides.
 */
export interface ConversionOptions {
    "preset": string;
    "processes": number;
    "threads": number;
    "jpegMode": string;
    "distance": number;
    "useDistance": boolean;
    "effort": number;
    "useEffort": boolean;
    "outputPolicy": string;
}

/**
 * ConversionSummary is emitted when a run finishes.
 */
export interface ConversionSummary {
    "total": number;
    "completed": number;
    "failed": number;
    "skipped": number;
    "cancelled": boolean;
    "bytesIn": number;
    "bytesOut": number;
}

/**
 * FilePreview is one item in the Basic view before conversion starts.
 */
export interface FilePreview {
    "path": string;
    "name": string;
    "format": string;
    "route": string;
    "size": number;
    "skip": boolean;
    "reason": string;
}

/**
 * FileUpdate is emitted when one file finishes.
 */
export interface FileUpdate {
    "input": string;
    "output": string;
    "format": string;
    "route": string;
    "inputSize": number;
    "outputSize": number;
    "skipped": boolean;
    "skipReason": string;
    "cancelled": boolean;
    "error": string;
}

/**
 * PresetSummary is the compact data shown by the Presets view.
 */
export interface PresetSummary {
    "name": string;
    "description": string;
    "policy": string;
}

/**
 * ProgressUpdate is emitted while a conversion is running.
 */
export interface ProgressUpdate {
    "total": number;
    "completed": number;
    "failed": number;
    "skipped": number;
    "inFlight": number;
    "bytesTotal": number;
    "bytesDone": number;
    "throughput": number;
    "etaSeconds": number;
    "coalesced": number;
    "paused": boolean;
    "percent": number;
}

/**
 * Status is a small snapshot the frontend can render on start.
 */
export interface Status {
    "unboundEntryPoints": string[] | null;
    "ready": boolean;
}

/**
 * ToolchainStatus is the compact toolchain state rendered by the Tools view.
 * Updates are notify-only: querying status never downloads or installs anything.
 */
export interface ToolchainStatus {
    "installedVersion": string;
    "cjxlVersion": string;
    "djxlVersion": string;
    "jxlinfoVersion": string;
    "latestVersion": string;
    "updateAvailable": boolean;
    "needsInstall": boolean;
    "flagsLocked": boolean;
    "flagBaseVersion": string;
    "flagToolVersion": string;
    "addedFlags": string[] | null;
    "removedFlags": string[] | null;
}
