// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Status is a small snapshot the frontend can render on start.
 */
export interface Status {
    /**
     * UnboundEntryPoints lists entry points that still need a preset binding.
     * While non-empty, jxleet must say so rather than run.
     */
    "unboundEntryPoints": string[] | null;

    /**
     * Ready is true when all three entry points are bound.
     */
    "ready": boolean;
}

/**
 * ToolchainStatus is the compact toolchain state rendered by the Tools view.
 * Updates are notify-only: querying status never downloads or installs anything.
 */
export interface ToolchainStatus {
    "installedVersion": string;
    "cjxlVersion": string;
    "djxlVersion": string;
    "jxlinfoVersion": string;
    "latestVersion": string;
    "updateAvailable": boolean;
    "needsInstall": boolean;
    "flagsLocked": boolean;
    "flagBaseVersion": string;
    "flagToolVersion": string;
    "addedFlags": string[] | null;
    "removedFlags": string[] | null;
}
