// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the root object bound to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddPaths queues paths handed over from this or another process invocation.
 * When a conversion is already running, the paths are added to that engine so
 * coalesced invocations share one run.
 */
export function AddPaths(paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2953239195, paths);
}

/**
 * CancelConversion cancels in-flight processes and queued work.
 */
export function CancelConversion(): $CancellablePromise<void> {
    return $Call.ByID(2964716064);
}

/**
 * ContextMenuRegistered reports whether the primary Explorer entry exists.
 */
export function ContextMenuRegistered(): $CancellablePromise<boolean> {
    return $Call.ByID(1144342962);
}

/**
 * CreatePreset creates a usable basic preset.
 */
export function CreatePreset(name: string, description: string): $CancellablePromise<void> {
    return $Call.ByID(2808243405, name, description);
}

/**
 * DeletePreset deletes a named preset.
 */
export function DeletePreset(name: string): $CancellablePromise<void> {
    return $Call.ByID(4177113838, name);
}

/**
 * DuplicatePreset duplicates a named preset.
 */
export function DuplicatePreset(name: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(2391082988, name, newName);
}

/**
 * GetActivePreset reports the preset currently used by an asynchronous run.
 */
export function GetActivePreset(): $CancellablePromise<string> {
    return $Call.ByID(2506442175);
}

/**
 * GetBindings returns the configured preset for each entry point.
 */
export function GetBindings(): $CancellablePromise<$models.Bindings> {
    return $Call.ByID(822407320);
}

/**
 * GetProgress returns the current progress snapshot, or an empty snapshot when
 * no conversion is running.
 */
export function GetProgress(): $CancellablePromise<$models.ProgressUpdate> {
    return $Call.ByID(1806053993);
}

/**
 * GetStatus reports whether the app is ready to run conversions.
 */
export function GetStatus(): $CancellablePromise<$models.Status> {
    return $Call.ByID(2946764936);
}

/**
 * GetToolchainStatus reports installed versions, the latest release, and the
 * Expert flag lock/diff. Errors are returned for display, never hidden.
 */
export function GetToolchainStatus(): $CancellablePromise<$models.ToolchainStatus> {
    return $Call.ByID(3508019419);
}

/**
 * InstallLatestToolchain performs the user-requested libjxl download and
 * atomic installation. It is deliberately not called by status queries.
 */
export function InstallLatestToolchain(): $CancellablePromise<string> {
    return $Call.ByID(1078493661);
}

/**
 * ListPresets returns valid stored presets.
 */
export function ListPresets(): $CancellablePromise<$models.PresetSummary[] | null> {
    return $Call.ByID(2651436498);
}

/**
 * OpenFiles opens the native multi-file/folder picker.
 */
export function OpenFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1594681061);
}

/**
 * OpenStorageLocation opens one of jxleet's storage directories in Explorer.
 */
export function OpenStorageLocation(location: string): $CancellablePromise<void> {
    return $Call.ByID(2196472704, location);
}

/**
 * PauseConversion pauses dispatching new files.
 */
export function PauseConversion(): $CancellablePromise<void> {
    return $Call.ByID(3136368964);
}

/**
 * PreviewPaths classifies files using the same preset/options as StartConversion.
 */
export function PreviewPaths(paths: string[] | null, options: $models.ConversionOptions): $CancellablePromise<$models.FilePreview[] | null> {
    return $Call.ByID(2233973306, paths, options);
}

/**
 * ReceivePaths accepts an external invocation, retaining its explicit preset
 * override until the frontend starts the run.
 */
export function ReceivePaths(paths: string[] | null, presetName: string): $CancellablePromise<void> {
    return $Call.ByID(4082249969, paths, presetName);
}

/**
 * RegisterContextMenu installs the per-user Explorer entries using the current
 * context-menu preset binding.
 */
export function RegisterContextMenu(): $CancellablePromise<void> {
    return $Call.ByID(286962749);
}

/**
 * RenamePreset renames a named preset.
 */
export function RenamePreset(name: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(869370011, name, newName);
}

/**
 * ResumeConversion resumes a paused conversion.
 */
export function ResumeConversion(): $CancellablePromise<void> {
    return $Call.ByID(98548325);
}

/**
 * SetBinding validates and persists one entry-point binding.
 */
export function SetBinding(entryPoint: string, presetName: string): $CancellablePromise<void> {
    return $Call.ByID(2914141111, entryPoint, presetName);
}

/**
 * StartConversion starts an asynchronous conversion; progress arrives through
 * Wails events so the UI remains responsive.
 */
export function StartConversion(paths: string[] | null, options: $models.ConversionOptions): $CancellablePromise<void> {
    return $Call.ByID(448384482, paths, options);
}

/**
 * TakePending returns and clears paths received before the frontend subscribed.
 */
export function TakePending(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1800653784);
}

/**
 * TakePendingPreset returns an external preset override received before the
 * frontend subscribed.
 */
export function TakePendingPreset(): $CancellablePromise<string> {
    return $Call.ByID(3054070023);
}

/**
 * UnregisterContextMenu removes the per-user Explorer entries.
 */
export function UnregisterContextMenu(): $CancellablePromise<void> {
    return $Call.ByID(3976869576);
}
