// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the root object bound to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddPaths queues paths handed over from this or another process invocation.
 * When a conversion is already running, the paths are added to that engine so
 * coalesced invocations share one run.
 */
export function AddPaths(paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2953239195, paths);
}

/**
 * CancelConversion cancels in-flight processes and queued work.
 */
export function CancelConversion(): $CancellablePromise<void> {
    return $Call.ByID(2964716064);
}

/**
 * ClearHistory removes every recorded conversion.
 */
export function ClearHistory(): $CancellablePromise<void> {
    return $Call.ByID(3663823565);
}

/**
 * ContextMenuRegistered reports whether the primary Explorer entry exists.
 */
export function ContextMenuRegistered(): $CancellablePromise<boolean> {
    return $Call.ByID(1144342962);
}

/**
 * CreatePreset writes the commented starter template as a new preset.
 */
export function CreatePreset(name: string, description: string): $CancellablePromise<void> {
    return $Call.ByID(2808243405, name, description);
}

/**
 * DeletePreset deletes a named preset.
 */
export function DeletePreset(name: string): $CancellablePromise<void> {
    return $Call.ByID(4177113838, name);
}

/**
 * DuplicatePreset duplicates a named preset.
 */
export function DuplicatePreset(name: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(2391082988, name, newName);
}

/**
 * GetActivePreset reports the preset currently used by an asynchronous run.
 */
export function GetActivePreset(): $CancellablePromise<string> {
    return $Call.ByID(2506442175);
}

/**
 * GetBindings returns the configured preset for each entry point.
 */
export function GetBindings(): $CancellablePromise<$models.Bindings> {
    return $Call.ByID(822407320);
}

/**
 * GetHistoryEntries returns all recorded conversions, newest first.
 */
export function GetHistoryEntries(): $CancellablePromise<$models.HistoryEntry[] | null> {
    return $Call.ByID(2402018238);
}

/**
 * GetPendingCollision returns the currently waiting output-exists prompt, or
 * nil. The frontend calls it once on load to recover a prompt that fired
 * before it subscribed to the event (early CLI run).
 */
export function GetPendingCollision(): $CancellablePromise<$models.CollisionPrompt | null> {
    return $Call.ByID(2095697683);
}

/**
 * GetPresetCore reads the editable core of a preset for the GUI controls.
 * Absent distance/effort report the cjxl defaults (1.0 / 7).
 */
export function GetPresetCore(name: string): $CancellablePromise<$models.PresetCore> {
    return $Call.ByID(3494567662, name);
}

/**
 * GetProgress returns the current progress snapshot, or an empty snapshot when
 * no conversion is running.
 */
export function GetProgress(): $CancellablePromise<$models.ProgressUpdate> {
    return $Call.ByID(1806053993);
}

/**
 * GetStatus reports whether the app is ready to run conversions.
 */
export function GetStatus(): $CancellablePromise<$models.Status> {
    return $Call.ByID(2946764936);
}

/**
 * GetToolchainStatus reports installed versions, the latest release, and the
 * Expert flag lock/diff. Errors are returned for display, never hidden.
 */
export function GetToolchainStatus(): $CancellablePromise<$models.ToolchainStatus> {
    return $Call.ByID(3508019419);
}

/**
 * InspectJXL returns verbose metadata for one existing JPEG XL file.
 */
export function InspectJXL(path: string): $CancellablePromise<string> {
    return $Call.ByID(3229468240, path);
}

/**
 * InstallLatestToolchain performs the user-requested libjxl download and
 * atomic installation. It is deliberately not called by status queries.
 * Download and install progress is emitted as "toolchain-progress" events.
 */
export function InstallLatestToolchain(): $CancellablePromise<string> {
    return $Call.ByID(1078493661);
}

/**
 * ListCJXLFlags returns the generated cjxl flag surface and its help text.
 */
export function ListCJXLFlags(): $CancellablePromise<$models.FlagInfo[] | null> {
    return $Call.ByID(3994931890);
}

/**
 * ListPresets returns valid stored presets.
 */
export function ListPresets(): $CancellablePromise<$models.PresetSummary[] | null> {
    return $Call.ByID(2651436498);
}

/**
 * OpenFiles opens the native multi-file picker.
 */
export function OpenFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1594681061);
}

/**
 * OpenFolders opens the native multi-folder picker.
 */
export function OpenFolders(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2368652971);
}

/**
 * OpenPresetInEditor opens a preset's YAML file in the system default editor.
 */
export function OpenPresetInEditor(name: string): $CancellablePromise<void> {
    return $Call.ByID(1010812251, name);
}

/**
 * OpenStorageLocation opens one of jxleet's storage directories in Explorer.
 */
export function OpenStorageLocation(location: string): $CancellablePromise<void> {
    return $Call.ByID(2196472704, location);
}

/**
 * PauseConversion pauses dispatching new files.
 */
export function PauseConversion(): $CancellablePromise<void> {
    return $Call.ByID(3136368964);
}

/**
 * PreviewCommands returns the resolved command preview for every preset rule.
 */
export function PreviewCommands(options: $models.ConversionOptions): $CancellablePromise<$models.CommandPreview[] | null> {
    return $Call.ByID(1100339228, options);
}

/**
 * PreviewPaths classifies files using the same preset/options as StartConversion.
 */
export function PreviewPaths(paths: string[] | null, options: $models.ConversionOptions): $CancellablePromise<$models.FilePreview[] | null> {
    return $Call.ByID(2233973306, paths, options);
}

/**
 * ReceivePaths accepts an external invocation. When a conversion is running and
 * the preset matches, paths are coalesced into it. Otherwise a fresh run is
 * started automatically so external callers (Lightroom, CLI) never have to be
 * triggered manually — the GUI-bound preset binding is used when no explicit
 * --preset was supplied.
 */
export function ReceivePaths(paths: string[] | null, presetName: string): $CancellablePromise<void> {
    return $Call.ByID(4082249969, paths, presetName);
}

/**
 * RegisterContextMenu installs the per-user Explorer entries using the current
 * context-menu preset binding.
 */
export function RegisterContextMenu(): $CancellablePromise<void> {
    return $Call.ByID(286962749);
}

/**
 * RenamePreset renames a named preset.
 */
export function RenamePreset(name: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(869370011, name, newName);
}

/**
 * ResolveCollision answers the outstanding output-exists prompt. Actions are
 * "overwrite", "overwrite-all", "skip" and "skip-all".
 */
export function ResolveCollision(action: string): $CancellablePromise<void> {
    return $Call.ByID(1261619658, action);
}

/**
 * ResumeConversion resumes a paused conversion.
 */
export function ResumeConversion(): $CancellablePromise<void> {
    return $Call.ByID(98548325);
}

/**
 * SavePresetOutput persists output policy and collision handling of a writable
 * preset. Saving re-marshals the YAML and drops any comments in that file;
 * comment-heavy, hand-edited presets should be changed in the editor instead.
 */
export function SavePresetOutput(name: string, policy: string, collision: string): $CancellablePromise<void> {
    return $Call.ByID(445715341, name, policy, collision);
}

/**
 * SetBinding validates and persists one entry-point binding.
 */
export function SetBinding(entryPoint: string, presetName: string): $CancellablePromise<void> {
    return $Call.ByID(2914141111, entryPoint, presetName);
}

/**
 * StartConversion starts an asynchronous conversion; progress arrives through
 * Wails events so the UI remains responsive.
 */
export function StartConversion(paths: string[] | null, options: $models.ConversionOptions): $CancellablePromise<void> {
    return $Call.ByID(448384482, paths, options);
}

/**
 * TakePending returns and clears paths received before the frontend subscribed.
 */
export function TakePending(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1800653784);
}

/**
 * TakePendingPreset returns an external preset override received before the
 * frontend subscribed.
 */
export function TakePendingPreset(): $CancellablePromise<string> {
    return $Call.ByID(3054070023);
}

/**
 * UnregisterContextMenu removes the per-user Explorer entries.
 */
export function UnregisterContextMenu(): $CancellablePromise<void> {
    return $Call.ByID(3976869576);
}
